### ISSUE TITLE
Meta-issue for getting SCP production-ready

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse-config-generator#25]
I've done a bit of testing to check on the current state of this repo. I've found a number of issues peppered about, but only one major blocker. That would be https://github.com/matrix-org/synapse-config-generator/issues/23, which makes this tool incompatible with Synapse v1.13.0+.

However, after working around that one issue I was able to get a configuration generated and Synapse automatically started successfully :tada: 

There are a few tasks that I think would need to be taken care off before a first release:

- [ ] [Reverse Proxy configuration doesn't take into account delegation choices](https://github.com/matrix-org/synapse-config-generator/issues/21)
- [ ] [Decide what to do with the ACME section](https://github.com/matrix-org/synapse-config-generator/issues/19)
- [ ] [Webserver isn't hosting any files](https://github.com/matrix-org/synapse-config-generator/issues/11)
- [ ] [Client well-known delegation generates invalid JSON](https://github.com/matrix-org/synapse-config-generator/issues/22)
- [ ] [Update link to Synapse delegation docs](https://github.com/matrix-org/synapse-config-generator/pull/18)
- [ ] [Improve readme](https://github.com/matrix-org/synapse-config-generator/pull/10)
- [ ] [Add CI](https://github.com/matrix-org/synapse-config-generator/issues/28)

Along with some nice-to-have's:

- [ ] [Config directory should be created if it doesn't exist](https://github.com/matrix-org/synapse-config-generator/issues/17)
- [ ] [synapse-config-generator script doesn't mark config_dir as a required argument](https://github.com/matrix-org/synapse-config-generator/issues/16)

Otherwise it looks like there's some Node (and probably some Python) dependency bumps that should happen. Additionally a comb over the wording and codebase for cleanup/maintenance tasks wouldn't go amiss).
